/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import database.Database;
import entities.Venda;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class ScreenCadastrarVenda extends javax.swing.JFrame {
    
    

    /**
     * Creates new form ScreenCadastrarVenda
     */
    public ScreenCadastrarVenda() {
        initComponents();
        
        inicializarCamposCustomizados();
        
        txtPagamento.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verificarPagamento();
            }
        });
        
        //jBCadastrar2.setOpaque(false);   
        //jBCadastrar2.setContentAreaFilled(false);
        //jBCadastrar2.setBorderPainted(false);
        
    }
    
    private void inicializarCamposCustomizados() {
      
        for (int i = 1; i <= 12; i++) {
            comboBoxParcelas.addItem(String.valueOf(i));
        }

      
        comboBoxParcelas.setEnabled(false);
    }

    private void verificarPagamento() {
        String pagamento = txtPagamento.getText().toLowerCase();

        if (pagamento.equals("cartão")) {
            comboBoxParcelas.setEnabled(true);  
        } else if (pagamento.equals("dinheiro") || pagamento.equals("transferência")) {
            comboBoxParcelas.setEnabled(false);  
        } else {
            JOptionPane.showMessageDialog(this, "Método de pagamento inválido. Use: cartão, dinheiro ou transferência.");
            txtPagamento.setText("");  // 
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCadastrar2 = new javax.swing.JButton();
        txtPagamento = new javax.swing.JTextField();
        comboBoxUnidade = new javax.swing.JComboBox<>();
        txtIdCliente = new javax.swing.JTextField();
        txtMaterial = new javax.swing.JTextField();
        spinnerQuantidade = new javax.swing.JSpinner();
        comboBoxParcelas = new javax.swing.JComboBox<>();
        txtDataVenda = new javax.swing.JFormattedTextField();
        txtPreco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar venda");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCadastrar2.setBackground(new java.awt.Color(51, 51, 51));
        jBCadastrar2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jBCadastrar2.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar2.setText("Cadastrar");
        jBCadastrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCadastrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBCadastrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 250, 80));

        txtPagamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 50));

        comboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KG", "TONELADAS" }));
        comboBoxUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxUnidadeActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 120, 60));

        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 50));

        txtMaterial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 190, 50));

        spinnerQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spinnerQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        getContentPane().add(spinnerQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 90, 50));

        comboBoxParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        comboBoxParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxParcelasActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, 60));

        try {
            txtDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtDataVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 50));

        txtPreco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("R$:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 50, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("ID do cliente:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Data da venda:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Pagamento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Material:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 120, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Preço:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 80, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Quantidade:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Unidade:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 120, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Parcelas:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxUnidadeActionPerformed

    private void comboBoxParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxParcelasActionPerformed

    private void jBCadastrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrar2ActionPerformed
        // TODO add your handling code here:
        
        int idCliente = Integer.parseInt(txtIdCliente.getText());
        String dataVenda = txtDataVenda.getText();
        String pagamento = txtPagamento.getText();
        int parcelas = Integer.parseInt(comboBoxParcelas.getSelectedItem().toString());
        String material = txtMaterial.getText();
        int quantidade = (int) spinnerQuantidade.getValue();
        String unidade = comboBoxUnidade.getSelectedItem().toString();
        double preco = Double.parseDouble(txtPreco.getText());

    Venda venda = new Venda(idCliente, dataVenda, pagamento, parcelas, material, quantidade, unidade, preco, "11/11/2024");
    Database.adicionarVenda(venda);

    
    JOptionPane.showMessageDialog(this, "Salvando venda para o cliente ID: " + idCliente);
    }//GEN-LAST:event_jBCadastrar2ActionPerformed

    private void txtPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoActionPerformed
        // TODO add your handling code here:
        
        txtPagamento.addKeyListener(new KeyAdapter() {
    public void keyReleased(KeyEvent e) {
        if (txtPagamento.getText().equalsIgnoreCase("Cartão")) {
            comboBoxParcelas.setEnabled(true);
        } else {
            comboBoxParcelas.setEnabled(false);
            comboBoxParcelas.setSelectedIndex(0);
        }
    }
});
        
    }//GEN-LAST:event_txtPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenCadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenCadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenCadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenCadastrarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenCadastrarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxParcelas;
    private javax.swing.JComboBox<String> comboBoxUnidade;
    private javax.swing.JButton jBCadastrar2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spinnerQuantidade;
    private javax.swing.JFormattedTextField txtDataVenda;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtPagamento;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
